apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  SECRET_KEY: "your-django-secret-key"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "securepassword"
  POSTGRES_DB: "djangodb"
